# Generated by Django 4.1 on 2022-09-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('lugar', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=5, null=True)),
                ('aforo', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('edad_minima', models.CharField(blank=True, max_length=50, null=True)),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('puntaje', models.CharField(blank=True, max_length=50, null=True)),
                ('elenco', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('equipos', models.CharField(blank=True, max_length=500, null=True)),
                ('deporte', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
