# Generated by Django 4.1 on 2022-09-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Entrega1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, max_length=10, null=True)),
                ('lugar', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicio', models.TimeField(blank=True, max_length=5, null=True)),
                ('equipo1', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo2', models.CharField(blank=True, max_length=100, null=True)),
                ('deporte', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, max_length=10, null=True)),
                ('lugar', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicio', models.TimeField(blank=True, max_length=5, null=True)),
                ('edad_minima', models.IntegerField(blank=True, max_length=50, null=True)),
                ('puntaje', models.IntegerField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teatro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, max_length=10, null=True)),
                ('lugar', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicio', models.TimeField(blank=True, max_length=5, null=True)),
                ('elenco', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='eventos',
        ),
    ]
