# Generated by Django 4.1 on 2022-09-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Entrega1', '0002_deporte_peliculas_teatro_delete_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='edad_minima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
