# Generated by Django 4.1 on 2022-09-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Entrega1', '0003_alter_peliculas_edad_minima_alter_peliculas_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
