# Generated by Django 4.1 on 2022-09-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Entrega1', '0004_alter_peliculas_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('cuerpo', models.TextField()),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
