# Generated by Django 4.1 on 2022-09-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Entrega1', '0005_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento_db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('propietario', models.CharField(max_length=100, null=True)),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('subtitulo', models.CharField(max_length=100, null=True)),
                ('cuerpo', models.TextField()),
                ('autor', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='deporte',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='peliculas',
        ),
        migrations.DeleteModel(
            name='teatro',
        ),
    ]
