# Generated by Django 4.1 on 2022-09-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Entrega1', '0006_evento_db_delete_deporte_delete_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento_db',
            name='cuerpo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
