# Generated by Django 4.1 on 2022-09-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Entrega1', '0007_alter_evento_db_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento_db',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
