# Generated by Django 4.1 on 2022-09-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Entrega1', '0008_alter_evento_db_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento_db',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
