# Generated by Django 4.1 on 2022-10-03 23:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Entrega1', '0009_alter_evento_db_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento_db',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
